#if defined _respawn_unlocker_entity_included
 #endinput
#endif
#define _respawn_unlocker_entity_included

#define WORLD 0
#define INVALID_HAMMER_ID 0
#define CLASS_NAME_SIZE 32

#define ENTITY_PROPERTY_VEC_ORIGIN "m_vecOrigin"
#define ENTITY_PROPERTY_VEC_MINS "m_vecMins"
#define ENTITY_PROPERTY_VEC_MAXS "m_vecMaxs"
#define ENTITY_PROPERTY_COLLISION_GROUP "m_CollisionGroup"
#define ENTITY_PROPERTY_HAMMER_ID "m_iHammerID"

#define COLLISION_GROUP_NONE 0
#define COLLISION_GROUP_IN_VEHICLE 10
#define COLLISION_GROUP_OBJECT 21
