#if defined _respawn_unlocker_menu_included
 #endinput
#endif
#define _respawn_unlocker_menu_included

#define TEXT_BUFFER_MAX_SIZE (256 * 4)
#define MENU_ITEM_INFO_MAX_SIZE 32

#define RESPAWN_UNLOCKER "Respawn unlocker"
#define CRATES_MANAGEMENT "Crates management"
#define TRIGGERS_MANAGEMENT "Triggers management"

#define ITEM_CRATE_ADD "Add crate"
#define ITEM_CRATE_REMOVE "Remove crate"
#define ITEM_CRATES_SHOW "Show crates"
#define ITEM_CRATES_HIDE "Hide crates"
#define ITEM_CRATES_LOAD "Load crates"
#define ITEM_CRATES_SAVE "Save crates"

#define ITEM_TRIGGER_ADD "Add trigger to list"
#define ITEM_TRIGGER_REMOVE "Remove trigger from list"
#define ITEM_TRIGGERS_LOAD "Load triggers"
#define ITEM_TRIGGERS_SAVE "Save triggers"

#define ADMIN_MENU "adminmenu"
