#if defined _respawn_unlocker_menu_included
 #endinput
#endif
#define _respawn_unlocker_menu_included

#define INFO_SIZE 128
#define ITEM_SIZE 128

#define RESPAWN_UNLOCKER "Respawn unlocker"
#define RESPAWN_LOCK "Lock respawn"
#define RESPAWN_UNLOCK "Unlock respawn"
#define TRIGGERS "Triggers"
#define TRIGGER_MARK "Mark trigger"
#define TRIGGER_UNMARK "Unmark trigger"
#define TRIGGERS_SAVE "Save triggers"
#define TRIGGERS_LOAD "Load triggers"
