#if defined _respawn_unlocker_menu_included
 #endinput
#endif
#define _respawn_unlocker_menu_included

#define INFO_SIZE 128
#define ITEM_SIZE 128

#define RESPAWN_UNLOCKER "Respawn unlocker"
#define RESPAWN_LOCK "Lock respawn"
#define RESPAWN_UNLOCK "Unlock respawn"

#define WALLS "Walls"
#define WALLS_ENABLE "Enable walls"
#define WALLS_DISABLE "Disable walls"

#define TRIGGERS "Triggers"
#define TRIGGER "Trigger"
#define TRIGGER_MARK "Mark trigger"
#define TRIGGER_UNMARK "Unmark trigger"
#define TRIGGER_SHOW "Show trigger"
#define TRIGGERS_ENABLE "Enable triggers"
#define TRIGGERS_DISABLE "Disable triggers"
#define TRIGGERS_SAVE "Save triggers"
#define TRIGGERS_LOAD "Load triggers"

#define CATAPULTS "Catapults"
#define CATAPULT "Catapult"
#define CATAPULT_ADD "Add catapult"
#define CATAPULT_LIST "Catapult list"
#define CATAPULT_ENABLE "Enable catapult"
#define CATAPULT_DISABLE "Disable catapult"
#define CATAPULT_SET_ORIGIN "Set catapult origin"
#define CATAPULT_SET_HEIGHT "Set catapult height"
#define CATAPULT_SHOW "Show catapult"
#define CATAPULT_REMOVE "Remove catapult"
#define CATAPULTS_ENABLE "Enable catapults"
#define CATAPULTS_DISABLE "Disable catapults"
#define CATAPULTS_SAVE "Save catapults"
#define CATAPULTS_LOAD "Load catapults"
