#if defined _ru_menu_included
 #endinput
#endif
#define _ru_menu_included

#define RESPAWN_UNLOCKER "Respawn unlocker"

#define ITEM_EDITOR_ENABLE "Enable editor"
#define ITEM_EDITOR_DISABLE "Disable editor"
#define ITEM_EDITOR_CRATE_ADD "Add crate"
#define ITEM_EDITOR_CRATE_REMOVE "Remove crate"
#define ITEM_CRATES_LOAD "Load crates"
#define ITEM_CRATES_SAVE "Save crates"

#define ADMIN_MENU "adminmenu"
