#if defined _ru_visualizer_included
 #endinput
#endif
#define _ru_visualizer_included

#define BEAM_START_FRAME 0
#define BEAM_FRAME_RATE 0
#define BEAM_LIFE_TIME 3.0
#define BEAM_WIDTH 2.0
#define BEAM_END_WIDTH BEAM_WIDTH
#define BEAM_FADE_LENGTH 0
#define BEAM_AMPLITUDE 0.0
#define BEAM_SPEED 0
#define BEAM_COLOR_RED 255
#define BEAM_COLOR_GREEN 255
#define BEAM_COLOR_BLUE 0
#define BEAM_COLOR_ALPHA 255
